# Generated by Django 3.1.2 on 2021-01-30 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyses', '0002_auto_20210130_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt_ast',
            name='alt_ast_time',
            field=models.TimeField(default='12:00:00', verbose_name='Godzina badania'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crpanalysis',
            name='crp_time',
            field=models.TimeField(default='12:00:00', verbose_name='Godzina badania'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crpanalysis',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urineanalisis',
            name='urine_time',
            field=models.TimeField(default='12:00:00', verbose_name='Godzina badania'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alt_ast',
            name='alt_ast_date',
            field=models.DateField(verbose_name='Data badania'),
        ),
        migrations.AlterField(
            model_name='crpanalysis',
            name='crp_date',
            field=models.DateField(verbose_name='Data badania'),
        ),
        migrations.AlterField(
            model_name='urineanalisis',
            name='urine_date',
            field=models.DateField(verbose_name='Data badania'),
        ),
    ]
