# Generated by Django 3.1.2 on 2020-10-23 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(max_length=20, verbose_name='Typ protokołu')),
                ('start_date', models.DateField(verbose_name='Data rozpoczecia')),
                ('end_date', models.DateTimeField(verbose_name='Data zakończenia')),
                ('supp_treatment_start', models.DateTimeField(verbose_name='Data rozpoczęcia podtrzymania')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protokół',
                'verbose_name_plural': 'Protokoły',
            },
        ),
    ]
