# Generated by Django 3.1.2 on 2020-10-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineDose',
        ),
    ]
